// kbpkg — mock registry data
window.KBPKG_PACKAGES = [
  {
    id: 'utils/fmt', name: 'utils/fmt', version: '1.3.0', updated: '3 days ago',
    desc: 'Deterministic code formatter for kBenestad repos. Zero config, fast, opinionated.',
    tags: ['cli', 'formatting', 'typescript'], installs: '1.2k', license: 'MIT',
    repo: 'git@kb:utils/fmt', size: '12 kB', deps: 0, owner: 'Karl Benestad',
    readme: 'A deterministic formatter. Point it at a directory and it rewrites every file to the canonical style — no options to argue about.',
    versions: [['1.3.0','3 days ago'],['1.2.1','3 weeks ago'],['1.2.0','2 months ago'],['1.1.0','5 months ago']],
    dependencies: [],
  },
  {
    id: 'core/log', name: 'core/log', version: '2.4.0', updated: '1 day ago',
    desc: 'Structured, leveled logging with pretty terminal output and JSON for production.',
    tags: ['logging', 'observability'], installs: '3.8k', license: 'MIT',
    repo: 'git@kb:core/log', size: '24 kB', deps: 1, owner: 'Karl Benestad',
    readme: 'Leveled logging that looks good in a terminal and parses cleanly in production. Tiny surface area.',
    versions: [['2.4.0','1 day ago'],['2.3.0','1 month ago'],['2.0.0','4 months ago']],
    dependencies: [['ansi/color','^1.0.0']],
  },
  {
    id: 'git/sync', name: 'git/sync', version: '0.9.2', updated: '6 days ago',
    desc: 'Bidirectional sync between kbpkg registry mirrors over plain git remotes.',
    tags: ['git', 'registry', 'sync'], installs: '640', license: 'Apache-2.0',
    repo: 'git@kb:git/sync', size: '58 kB', deps: 2, owner: 'kBenestad',
    readme: 'Keeps two registry mirrors in lock-step using nothing but git. Resolves conflicts by version precedence.',
    versions: [['0.9.2','6 days ago'],['0.9.0','3 weeks ago'],['0.8.0','2 months ago']],
    dependencies: [['core/log','^2.0.0'],['utils/fmt','^1.0.0']],
  },
  {
    id: 'ansi/color', name: 'ansi/color', version: '1.0.0', updated: '2 months ago',
    desc: 'Minimal ANSI color + style helpers. No dependencies, tree-shakeable.',
    tags: ['cli', 'terminal'], installs: '5.1k', license: 'MIT',
    repo: 'git@kb:ansi/color', size: '4 kB', deps: 0, owner: 'Karl Benestad',
    readme: 'Just enough ANSI to make terminal output readable. Four functions, no theme system.',
    versions: [['1.0.0','2 months ago'],['0.4.0','6 months ago']],
    dependencies: [],
  },
  {
    id: 'cms/md', name: 'cms/md', version: '0.6.1', updated: '2 weeks ago',
    desc: 'Markdown + front-matter parser powering mdcms. Multilingual-aware.',
    tags: ['markdown', 'cms', 'i18n'], installs: '410', license: 'MIT',
    repo: 'git@kb:cms/md', size: '31 kB', deps: 1, owner: 'kBenestad',
    readme: 'Parses Markdown with YAML front-matter and a light multilingual convention. Built for mdcms.',
    versions: [['0.6.1','2 weeks ago'],['0.6.0','1 month ago']],
    dependencies: [['utils/fmt','^1.2.0']],
  },
  {
    id: 'pdf/invoice', name: 'pdf/invoice', version: '1.1.0', updated: '5 weeks ago',
    desc: 'Render invoices to print-ready PDF. Used by the invoice and reimburse apps.',
    tags: ['pdf', 'invoicing'], installs: '290', license: 'MIT',
    repo: 'git@kb:pdf/invoice', size: '88 kB', deps: 1, owner: 'Karl Benestad',
    readme: 'Takes a small JSON document and renders a clean, print-ready PDF invoice. Currency- and locale-aware.',
    versions: [['1.1.0','5 weeks ago'],['1.0.0','3 months ago']],
    dependencies: [['core/log','^2.0.0']],
  },
];
